# 新窗口打开目录
protocol file
mime inode/directory
action launch --type=os-window --cwd "$FILE_PATH"

protocol file
mime image/*
action launch --type=overlay kitten icat --hold "$FILE_PATH"

# 用桌面应用打开
protocol file
mime video/*, audio/*, application/*, text/html
action launch --type=background kde-open "$FILE_PATH"

# 编辑带行号的文件
protocol file
fragment_matches [0-9]+
action launch --type=overlay $EDITOR +$FRAGMENT "$FILE_PATH"

# 编辑任意文件
protocol file
action launch --type=overlay $EDITOR "$FILE_PATH"
