#!/bin/sh

resources=${XDG_CONFIG_HOME}/X11/resources
if [ -f "$resources" ]; then xrdb -merge "$resources"; fi
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && source "$f"
	done; unset f
fi

source ${XDG_CONFIG_HOME}/X11/profile

if [[ -n "$@" ]]; then
	exec "$@"
fi
