#################################
#             Shadows           #
#################################

shadow = true
shadow-radius = 32
shadow-offset-x = -32
shadow-offset-y = -32
shadow-opacity = 0.48

shadow-exclude = [
    "argb && (
        (window_type = 'menu' && class_g != 'fcitx')
        || window_type = 'popup_menu'
        || window_type = 'tooltip'
        || (window_type = 'combo' && class_g != 'fcitx')
        || (window_type = 'utility' && class_g != 'Dunst')
    )"
    , "QTILE_INTERNAL = 1"
    , "class_g = 'TelegramDesktop' && argb && override_redirect"
]

#################################
#           Fading              #
#################################

fading = true
fade-delta = 4

#################################
#           Corners             #
#################################

corner-radius = 12

rounded-corners-exclude = [
    "QTILE_INTERNAL"
    , "IS_FLOATING@ = 0"
    , "class_g = 'kitty'"
    , "class_g = 'mpv'"
];

#################################
#            Blur               #
#################################

blur-method = "dual_kawase"
blur-strength = 6
blur-background-exclude = [
    "argb && override_redirect"
    , "window_type != 'normal'"
];

#################################
#       General Settings        #
#################################

backend = "glx"
vsync = true
use-damage = true
unredir-if-possible = true

use-ewmh-active-win = true
mark-ovredir-focused = true
detect-rounded-corners = true
detect-client-opacity = true
detect-transient = true
detect-client-leader = true
